baseURL: /
title: Daniel Franzani
theme: hugo-theme-m10c
paginate: 11
menu:
  main:
    - identifier: home
      name: Temas
      url: /
      weight: 1
    - identifier: tags
      name: Etiquetas
      url: /tags/
      weight: 2
    - identifier: about
      name: Sobre mi
      url: /about/
      weight: 3
params:
  author: Daniel Franzani
  avatar: foto.png
  description: Blogdown + Github + Netlify
  menu_item_separator: ', '
  social:
    - icon: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/dfranzani/
    - icon: github
      name: Github
      url: https://github.com/Dfranzani
  style:
    darkestColor: "#232323"
    darkColor: "#262C3B"
    lightColor: "#CFCAC9"
    lightestColor: "#D3D2D2"
    primaryColor: "#4EBBBB"
